name: Rust

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: rustup target add ${{ env.BUILD_TARGET }}
    - uses: actions/checkout@v3
    - name: Build Release
      run: cargo build --release --target ${{ env.BUILD_TARGET }}
